In [ ]:
import numpy as np

In [ ]:
def softmax(X: np.ndarray):
  return np.exp(X)/np.sum(np.exp(X))

In [ ]:
softmax(np.array([1, 2, 3]))

array([0.09003057, 0.24472847, 0.66524096])

In [ ]:
# ouch
softmax(np.array([1, 2, 5000]))

<ipython-input-2-07948f78ad89>:2: RuntimeWarning: overflow encountered in exp
  return np.exp(X)/np.sum(np.exp(X))
<ipython-input-2-07948f78ad89>:2: RuntimeWarning: invalid value encountered in divide
  return np.exp(X)/np.sum(np.exp(X))


array([ 0.,  0., nan])

In [ ]:
def softmax_with_trick(X: np.ndarray):
  max_X = np.max(X)
  return np.exp(X - max_X)/np.sum(np.exp(X - max_X))

In [ ]:
softmax_with_trick(np.array([1, 2, 3]))

array([0.09003057, 0.24472847, 0.66524096])

In [ ]:
softmax_with_trick(np.array([1, 2, 5000]))

array([0., 0., 1.])

In [ ]:
def softmax_with_mask_naive(X: np.ndarray, M: np.ndarray):
  exp_X = np.exp(X)
  masked_exp_X = exp_X * M
  return masked_exp_X/np.sum(masked_exp_X)

In [ ]:
softmax_with_mask_naive(np.array([1, 2, 3]),np.array([1., 1., 0.]))

array([0.26894142, 0.73105858, 0.        ])

In [ ]:
#ouch
softmax_with_mask_naive(np.array([1, 20000, 3]),np.array([1., 1., 0.]))

<ipython-input-8-c53689d79861>:2: RuntimeWarning: overflow encountered in exp
  exp_X = np.exp(X)
<ipython-input-8-c53689d79861>:4: RuntimeWarning: invalid value encountered in divide
  return masked_exp_X/np.sum(masked_exp_X)


array([ 0., nan,  0.])

In [ ]:
def softmax_with_mask_naive_with_max_trick(X: np.ndarray, M: np.ndarray):
  max_X = np.max(X)
  exp_X = np.exp(X - max_X)
  masked_exp_X = exp_X * M
  return masked_exp_X/np.sum(masked_exp_X)

In [ ]:
softmax_with_mask_naive_with_max_trick(np.array([1, 2, 3]),np.array([1., 1., 0.]))

array([0.26894142, 0.73105858, 0.        ])

In [ ]:
softmax_with_mask_naive_with_max_trick(np.array([1, 20000, 3]),np.array([1., 1., 0.]))

array([0., 1., 0.])

In [ ]:
softmax_with_mask_naive_with_max_trick(np.array([1, 2, 30000]),np.array([1., 1., 0.]))

<ipython-input-11-5056f6a7939d>:5: RuntimeWarning: invalid value encountered in divide
  return masked_exp_X/np.sum(masked_exp_X)


array([nan, nan, nan])

In [ ]:
def softmax_with_mask_naive_with_max_trick2(X: np.ndarray, M: np.ndarray):
  X = X * M
  max_X = np.max(X)
  exp_X = np.exp(X - max_X)
  masked_exp_X = exp_X * M
  return masked_exp_X/np.sum(masked_exp_X)

In [ ]:
softmax_with_mask_naive_with_max_trick2(np.array([1, 2, 3]),np.array([1., 1., 0.]))

array([0.26894142, 0.73105858, 0.        ])

In [ ]:
softmax_with_mask_naive_with_max_trick2(np.array([1, 20000, 3]),np.array([1., 1., 0.]))

array([0., 1., 0.])

In [ ]:
softmax_with_mask_naive_with_max_trick2(np.array([1, 2, 30000]),np.array([1., 1., 0.]))

array([0.26894142, 0.73105858, 0.        ])

In [ ]:
#ouch
softmax_with_mask_naive_with_max_trick2(np.array([-2222, -2222, 30000]),np.array([1., 1., 0.]))

<ipython-input-15-6f8718711ea8>:6: RuntimeWarning: invalid value encountered in divide
  return masked_exp_X/np.sum(masked_exp_X)


array([nan, nan, nan])

In [ ]:
def acceptable_softmax_with_mask(X: np.ndarray, M: np.ndarray):
  positive_X = X - np.min(X)
  masked_positive_X = positive_X * M
  max_X = np.max(masked_positive_X)
  exp_X = np.exp(masked_positive_X - max_X)
  masked_exp_X = exp_X * M
  return masked_exp_X/np.sum(masked_exp_X)

In [ ]:
acceptable_softmax_with_mask(np.array([1, 2, 3]),np.array([1., 1., 0.]))

array([0.26894142, 0.73105858, 0.        ])

In [ ]:
acceptable_softmax_with_mask(np.array([1, 20000, 3]),np.array([1., 1., 0.]))

array([0., 1., 0.])

In [ ]:
acceptable_softmax_with_mask(np.array([1, 2, 30000]),np.array([1., 1., 0.]))

array([0.26894142, 0.73105858, 0.        ])

In [ ]:
acceptable_softmax_with_mask(np.array([-2222, -2222, 30000]),np.array([1., 1., 0.]))

array([0.5, 0.5, 0. ])

In [ ]:
# proposition alternative de votre camarade :)
def acceptable_softmax_with_mask_alt(X: np.ndarray, M: np.ndarray):
    max_X = np.max(X[M != 0])
    exp_X = np.exp(X - max_X)
    exp_X[M == 0] = 0
    masked_exp_X = exp_X * M

    return masked_exp_X/np.sum(masked_exp_X)

In [ ]:
import tensorflow as tf

In [ ]:
sm_layer = tf.keras.layers.Softmax()

In [ ]:
sm_layer(np.array([18.0, 20, 22000, 25]), np.array([1.0, 1.0, 0.0, 1.0]))

<tf.Tensor: shape=(4,), dtype=float32, numpy=
array([9.0495922e-04, 6.6867946e-03, 0.0000000e+00, 9.9240828e-01],
      dtype=float32)>

In [ ]:
sm_layer(np.array([-222222.0, -222222, 22000, -222222]), np.array([1.0, 1.0, 0.0, 1.0]))

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([0.33333334, 0.33333334, 0.        , 0.33333334], dtype=float32)>

In [ ]:
# OMG ! une action interdite est jouée
sm_layer(np.array([-2e9, -2e9, 22000, -2e9]), np.array([1.0, 1.0, 0.0, 1.0]))

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([0., 0., 1., 0.], dtype=float32)>

In [ ]:
acceptable_softmax_with_mask(np.array([-2e9, -2e9, 22000, -2e9]), np.array([1.0, 1.0, 0.0, 1.0]))

array([0.33333333, 0.33333333, 0.        , 0.33333333])